# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpus',
            fields=[
                ('cpuid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('cpu', models.CharField(max_length=10)),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='disks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskid', models.PositiveSmallIntegerField()),
                ('space', models.PositiveSmallIntegerField()),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='engineer',
            fields=[
                ('engineerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.PositiveSmallIntegerField()),
                ('role', models.CharField(max_length=10)),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='envs',
            fields=[
                ('envid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('env', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('hostid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=50)),
                ('updatedate', models.DateField(auto_now=True)),
                ('statusid', models.PositiveSmallIntegerField()),
                ('regionid', models.PositiveSmallIntegerField()),
                ('envid', models.PositiveSmallIntegerField()),
                ('cpuid', models.PositiveSmallIntegerField()),
                ('memid', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hostsdisks',
            fields=[
                ('hostsdisksid', models.AutoField(primary_key=True, serialize=False)),
                ('hostid', models.PositiveSmallIntegerField()),
                ('diskid', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('memid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='net',
            fields=[
                ('ipid', models.AutoField(primary_key=True, serialize=False)),
                ('hostid', models.PositiveSmallIntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('nic', models.CharField(max_length=10)),
                ('mac', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('regionid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='service_engineer',
            fields=[
                ('service_engineerid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('serviceid', models.PositiveSmallIntegerField()),
                ('engineerid', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('serviceid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('statusid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
