# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0002_auto_20160706_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='cpu',
            field=models.CharField(max_length=50),
        ),
    ]
