# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0003_auto_20160706_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpus',
            old_name='cpu',
            new_name='cpuname',
        ),
        migrations.RenameField(
            model_name='cpus',
            old_name='number',
            new_name='vcpus',
        ),
    ]
